<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "csvfinisher"
 *
 * Auto generated by Extension Builder 2019-09-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'CSV - Finisher',
    'description' => 'Finisher für Formextension. Speichert Formulardaten in einer CSV-Datei und senden diese per Mail. ',
    'category' => 'services',
    'author' => 'Martin Giesen',
    'author_email' => 'martin@giesen-webentwicklung.de',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
